### ISSUE TITLE
最小限DB設計してrails g modelする

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/shukan#2]
# こんな感じ？
## User
* name:string （「にしこ」みたいなマルチバイト文字）
* token
* twitter_id:string, null: true
* screen_name:string, null:true（twitterのpandeiro245みたいな半角英数字）

## Category
* name
* parent_id:integer

※ AciveRecordではなくActiveHashを使う（ https://github.com/zilkey/active_hash ）

※運営が追加する
親：運動、勉強、楽器、アート、早寝早起き、料理
子：リングフィットアドベンチャー、英検2級、ギターの練習

## Goal
* goal:references
* user:references
* name:string（例：リングフィットアドベンチャーする）
* done_count: integer, defaut: 0（何回ゴールしたか）

## Event
* goal:references
* date_on:date

# メモ
* 全員が全員の達成を見られればよくてFollow、Friendみたいな概念は不要
* 習慣なので毎日が理想だができなくてもまた来週頑張ればOKというノリ

**Comment by kanahebi** [comment]
何回ゴールしたかの情報はまだいらないですかね？（何周目とか）

**Comment by pandeiro245** [comment]
@kanahebi たしかに！ `* done_count: integer, defaut: 0（何回ゴールしたか）` 追加しました
