### ISSUE TITLE
3. やったボタン

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/shukan#4]
# TODO
* [x] デザイン調整
* [x] カテゴリも表示

# 仕様
* 毎日0時になるとこの画面になる
* やったボタンのみが表示され、ほかはなにも見れない

# 現状

![image](https://user-images.githubusercontent.com/125965/115982226-6a4ccd00-a5d4-11eb-94f9-2cdc1511b513.png)

# こうなる予定

![image](https://user-images.githubusercontent.com/125965/115982233-75076200-a5d4-11eb-89e3-65556137d93d.png)

**Comment by pandeiro245** [comment]
@kanahebi ルーティングは `/goals/:id/events/new` で良いです？

**Comment by pandeiro245** [comment]
@seahorse-design ここにカテゴリ名も必要では？

**Comment by ishimaruco** [comment]
カテゴリ名入れました〜〜〜  
<img width="378" alt="スクリーンショット 2021-07-18 12 52 13" src="https://user-images.githubusercontent.com/12878889/126055127-d1599b2c-5e33-426e-8c4d-2008adb664ab.png">
